[project]
name = "nlp-algorithm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bson>=0.5.10",
    "fastapi>=0.127.0",
    "uvicorn[standard]>=0.40.0",
]
